-- create_table.sql
-- Create the EMPLOYEES table for PLSQL stored procedure examples.

CREATE TABLE employees (
    employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) UNIQUE NOT NULL,
    hire_date     DATE DEFAULT SYSDATE NOT NULL,
    salary        NUMBER(10,2) DEFAULT 0 NOT NULL,
    department    VARCHAR2(50)
);

COMMIT;
